### ISSUE TITLE
FR - Multimom Support

### ISSUE THREAD

**Issue by Rafcin** [tsivinsky/hi-mom#29]
We've been working on our own Mom mobile app and this package has been a great solution for some of our problems. However, it seems the package is limited to only returning one mom, what if we need to return more moms? We propose the mother function should be able to take a single mother or multiple mothers and return the proper mother or mothers. 

We think that the input for the mother should take an object or set of objects that have a mother parameter and a language parameter so you can return the mother with specific languages or a global option to translate all mothers to one language. 

`{ mother: 'Ana de Armas', language: 'EN' }`

**Comment by Diogenesoftoronto** [comment]
I think this is just the sort of bloat that is completely unnecessary for this library. It already does most of what it sets out to do why add more? Next thing you know its VISUAL COBOL.

**Comment by ChalanaN** [comment]
Done 🙌
